home_page: "https://www.railstutorial.org/"
help_page: "https://www.railstutorial.org/help"
book_page: "https://www.railstutorial.org/book"
contact_page: "https://www.railstutorial.org/contact"
screencasts: "https://screencasts.railstutorial.org/"
michaelhartl: "https://www.michaelhartl.com/"
width: "200px"
